---
name: CI

'on':
  pull_request:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: rudisimo.valheim

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the codebase.
        uses: actions/checkout@v2
        with:
          path: rudisimo.valheim

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies.
        run: |
          pip3 install -r requirements.txt -r requirements-lint.txt

      - name: Lint codebase.
        run: |
          yamllint .
          ansible-lint
